set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/dotfiles/config/.config/tmux/plugins'
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Indexing
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Switch window
bind -n M-H previous-window
bind -n M-L next-window

set -g @rose_pine_variant 'main'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_bar_bg_disabled_color_option 'default'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'mrjones2014/smart-splits.nvim'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'jrmoulton/tmux-sessionizer'
set -g @continuum-restore 'off'

# Theme
set -g @plugin 'rose-pine/tmux'

# just in case
set -g @yank_selection_mouse 'clipboard'

run '~/dotfiles/config/.config/tmux/plugins/tpm/tpm'

# Override theme status-right
set -g status-right '#(~/dotfiles/config/.config/tmux/plugins/tmux-
continuum/scripts/continuum_save.sh)#[fg=#e0def4] %I:%M %p'

# Status bar
set -g status-position top
set -g status-justify centre

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# tms
bind C-j display-popup -E "tms switch"
bind C-w display-popup -E "tms windows"
bind C-k confirm -p "Kill session? (y/N):" "run-shell 'tms-kill'"

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
